services:
  client:
    image: sfdeloach/fibi-overkill-react-server:0.0.0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CLIENT_PORT=${CLIENT_PORT}

  api:
    image: sfdeloach/fibi-overkill-api-server:0.0.0
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - API_PORT=${API_PORT}

  proxy:
    image: sfdeloach/fibi-overkill-nginx:0.0.0
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    depends_on:
      - client
      - api
    ports:
      - "8080:80"
