services:
  client:
    image: sfdeloach/fibi-overkill-react-server:0.0.0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  proxy:
    image: sfdeloach/fibi-overkill-nginx:0.0.0
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    depends_on:
      - client
    ports:
      - "8080:80"
